-- 20151026 장터 게시판 테이블 생성 ; 

CREATE TABLE `tbl_goods_info` (
	`GOODS_NUMSEQ` INT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '상품게시판 sequence',
	`GOODS_SUBJECT` VARCHAR(250) NOT NULL COMMENT '상품게시판 제목입력',
	`GOODS_WRITER` VARCHAR(15) NOT NULL COMMENT '상품게시판 작성자:외래키 USER ID',
	`GOODS_CONTENTS` TEXT NULL COMMENT '상품게시판 내용: 상품내용란',
	`GOODS_PICTURE` VARCHAR(20) NULL DEFAULT NULL COMMENT '상품게시판 사진: 사진추가',
	`GOODS_HITS` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '상품게시판 조회수',
	`GOODS_RECOMMENDATION` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '상품게시판 추천수',
	`GOODS_STOCKCOUNT` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '상품게시판 물품 재고',
	`GOODS_ORDERCOUNT` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '상품게시판 물품 주문수',
	`GOODS_REGDATE` DATETIME NOT NULL COMMENT '상품게시판 등록일',
	`GOODS_MODDATE` DATETIME NULL DEFAULT NULL COMMENT '상품게시판 수정일',
	`GOODS_STEP` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '상품게시판 0일 경우 상품게시판, 아닐 경우 댓글임을 의미',
	`GOODS_UPPER` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '상품게시판 GOODS_NUMSEQ를 참조: 0일 경우 게시판, 아닌 경우 상위 게시판을 참조하거나 상위 댓글을 참조',
	`GOODS_ROOTUPPER` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '상품게시판 GOODS_NUMSEQ를 참조: 0일 경우 게시판, 아닌 경우 최상위 게시판을 참조',
	PRIMARY KEY (`GOODS_NUMSEQ`),
	INDEX `FK_tbl_goods_info_tbl_user_info` (`GOODS_WRITER`),
	CONSTRAINT `FK_tbl_goods_info_tbl_user_info` FOREIGN KEY (`GOODS_WRITER`) REFERENCES `tbl_user_info` (`USER_ID`) ON UPDATE CASCADE ON DELETE CASCADE
);


COMMENT='장터 게시판'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
ROW_FORMAT=DEFAULT