--- 20151008 Byungwook update
--- create insert test, id duplication test complete

'CREATE TABLE TBL_USER_INFO (
	USER_NUMSEQ INT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
	USER_ID VARCHAR(15) NOT NULL,
	USER_PASSWORD VARCHAR(30) NOT NULL,
	USER_NAME VARCHAR(14) NOT NULL,
	USER_EMAIL1 VARCHAR(20) NOT NULL,
	USER_EMAIL2 VARCHAR(20) NOT NULL,
	USER_PHONENUMBER INT(11) UNSIGNED NOT NULL,
	USER_ADDRESS VARCHAR(100) NULL DEFAULT NULL,
	USER_BIRTHYEAR INT(4) UNSIGNED NOT NULL,
	USER_BIRTHMONTH INT(2) UNSIGNED NOT NULL,
	USER_BIRTHDATE INT(2) UNSIGNED NOT NULL,
	USER_BIRTHTYPE VARCHAR(6) NULL DEFAULT NULL,
	USER_SEX VARCHAR(6) NULL DEFAULT NULL,
	USER_GOODSCOUNT INT(20) UNSIGNED NOT NULL DEFAULT '0',
	USER_ORDERCOUNT INT(20) UNSIGNED NOT NULL DEFAULT '0',
	USER_BOARDCOUNT INT(20) UNSIGNED NOT NULL DEFAULT '0',
	PRIMARY KEY (`USER_NUMSEQ`),
	INDEX `USER_ID` (`USER_ID`)
);
'
-- 준갑이형 안녕하세요 한글 커밋입니다.

CREATE TABLE TBL_USER_INFO (
	USER_NUMSEQ INT(20) UNSIGNED NOT NULL AUTO_INCREMENT comment 'sequence number: primary key',
	USER_ID VARCHAR(15) NOT NULL comment 'user id: 사용자 아이디',
	USER_PASSWORD VARCHAR(30) NOT NULL comment 'user password: 사용자 비밀번호',
	USER_NAME VARCHAR(14) NOT NULL comment 'user name: 사용자 이름',
	USER_EMAIL1 VARCHAR(20) NOT NULL comment 'email1: email id',
	USER_EMAIL2 VARCHAR(20) NOT NULL comment 'email2: email address: ex naver.com',
	USER_PHONENUMBER INT(11) UNSIGNED NOT NULL comment 'phonenumber: 사용자 휴대전화번호',
	USER_ADDRESS VARCHAR(100) NULL DEFAULT NULL comment 'address: 사용자 주소 null가능;',
	USER_BIRTHYEAR INT(4) UNSIGNED NOT NULL comment 'birth year: 태어난 년도',
	USER_BIRTHMONTH INT(2) UNSIGNED NOT NULL comment 'birth month: 태어난 월',
	USER_BIRTHDATE INT(2) UNSIGNED NOT NULL comment 'birth date: 태어난 일',
	USER_BIRTHTYPE VARCHAR(6) NULL DEFAULT NULL comment 'birth type: 음력 = 1, 양력 = 2',
	USER_SEX VARCHAR(6) NULL DEFAULT NULL comment 'sex: 남자 = 1, 여자 = 2',	
	USER_GOODSCOUNT INT(20) UNSIGNED NOT NULL DEFAULT '0' comment 'goods count: 사용자가 올린 상품 갯수; 0이 디폴트',
	USER_ORDERCOUNT INT(20) UNSIGNED NOT NULL DEFAULT '0' comment 'order count: 사용자가 구매한 상품 갯수; 0이 디폴트',
	USER_BOARDCOUNT INT(20) UNSIGNED NOT NULL DEFAULT '0' comment 'board count: 사용자가 올린 게시글 갯수; 0이 디폴트',
	USER_REGDATE	DATETIME 	NOT NULL comment 'register date: 가입한 날',
	USER_AUTHORITY INT(10) UNSIGNED NOT NULL DEFAULT '1' COMMENT 'Authority: 권한설정, 1 일반, 2 블랙리스트, 0 관리',
	PRIMARY KEY (`USER_NUMSEQ`),
	INDEX `USER_ID` (`USER_ID`)
);