CREATE TABLE `tbl_user` (
	`USER_NUMSEQ` INT(50) NOT NULL AUTO_INCREMENT,
	`USER_ID` VARCHAR(50) NULL DEFAULT NULL,
	`USER_PASSWORD` VARCHAR(50) NULL DEFAULT NULL,
	`USER_NAME` VARCHAR(50) NULL DEFAULT NULL,
	`USER_COMPANY` VARCHAR(10) NULL DEFAULT NULL,
	`USER_REGDATE` DATE NULL DEFAULT NULL,
	PRIMARY KEY (`USER_SEQNUM`)
)