--- 10.8 봉재 : DB Table 생성을 위한 SQL 쿼리문
CREATE TABLE IF NOT EXISTS TBL_USER_INFO(
	NUM_SEQ 		INT(20)		NOT NULL PRIMARY KEY AUTO_INCREMENT,
	USER_ID 		VARCHAR(15) NOT NULL,
	USER_PASSWORD 	VARCHAR(30) NOT NULL,
	USER_NAME 		VARCHAR(14) NOT NULL,
	USER_EMAIL1 	VARCHAR(20) NOT NULL,
	USER_EMAIL2 	VARCHAR(20) NOT NULL,
	USER_PHONENUMBER INT(11)	NOT NULL,
	USER_ADDRESS	VARCHAR(100),
	USER_BIRTHYEAR	INT(4)		NOT NULL,
	USER_BIRTHMONTH	INT(2)		NOT NULL,
	USER_BIRTHDATE	INT(2)		NOT NULL,
	USER_BIRTHTYPE	VARCHAR(6),
	USER_SEX		VARCHAR(6),
	REG_DATE		DATETIME 	NOT NULL
);